name 'rlenglet-timezone'
version '0.1.0'
source 'https://github.com/rlenglet/puppet-timezone.git'
project_page 'https://github.com/rlenglet/puppet-timezone'
author 'Romain Lenglet'
license 'Apache License, Version 2.0'
summary 'Debian timezone config class'
description 'Class to (re)configure the timezone on Debian'
dependency 'rlenglet/debconf_package', '>= 0.1.0'
