name 'rlenglet-timezone'
version '0.1.1'
source 'https://github.com/rlenglet/puppet-timezone.git'
project_page 'https://github.com/rlenglet/puppet-timezone'
author 'Romain Lenglet'
license 'Apache License, Version 2.0'
summary 'System timezone configuration'
description 'Configures the system timezone'
dependency 'rlenglet/debconf_package', '>= 0.1.0'